export const newsData = [
  {
    "post_id": "443626877",
    "post_title": "25.10.29 수 업계 동향입니다.",
    "post_date": "2025-10-29",
    "source_url": "https://kakaohealthcare.agit.in/g/300070906/wall/443626877",
    "news_title": "1. 구글 AI 헬스 코칭",
    "news_content": "구글이 Gemini 기반 AI 헬스 코치를 공개, Fitbit과 Pixel Watch 사용자에게 맞춤형 운동, 수면, 영양 코칭을 제공한다.",
    "news_url": "https://www.mobihealthnews.com/news/google-debuts-gemini-powered-ai-health-coach-fitbit-and-pixel-watch-users",
    "demand": ["소비자(일반)"],
    "supply": ["AI/데이터기업"],
    "type": "AI코칭 서비스",
    "domain": "웰니스·운동·수면",
    "entity": ["Google", "Fitbit", "Pixel Watch"],
    "region": "글로벌",
    "category": "기술/AI·데이터",
    "service_form": "웨어러블+AI코칭",
    "summary": "AI를 활용해 사용자의 건강 데이터를 분석하고 개인별 맞춤 코칭을 제공하는 구글의 신규 헬스 서비스."
  },
  {
    "post_id": "443518704",
    "post_title": "25.10.28 화 업계 동향입니다.",
    "post_date": "2025-10-28",
    "source_url": "https://kakaohealthcare.agit.in/g/300070906/wall/443518704",
    "news_title": "2. 삼성 헬스케어 재편",
    "news_content": "삼성전자가 디지털 헬스케어 기업을 인수하며 그룹 차원의 헬스케어 사업 재편에 나섰다. 예방 중심의 헬스케어에 초점을 맞추고 있다.",
    "news_url": "https://www.investchosun.com/m/article.html?contid=2025102780068",
    "demand": ["의료기관", "소비자(일반)"],
    "supply": ["디바이스/IoT", "AI/데이터기업"],
    "type": "디지털 헬스케어 플랫폼",
    "domain": "예방의료",
    "entity": ["Samsung", "HealthTap"],
    "region": "국내",
    "category": "산업/시장동향",
    "service_form": "기기+플랫폼",
    "summary": "삼성이 헬스케어 기기와 플랫폼 중심으로 사업을 재편하며 예방 중심의 서비스 생태계를 강화하고 있다."
  },
  {
    "post_id": "443244729",
    "post_title": "25.10.24 금 업계 동향입니다.",
    "post_date": "2025-10-24",
    "source_url": "https://kakaohealthcare.agit.in/g/300070906/wall/443244729",
    "news_title": "3. 병원 밖 개입",
    "news_content": "카카오헬스케어는 연속혈당측정기(CGM)와 AI 예측 모델을 활용해 질병 발병 이전 단계에서 개입하는 ‘병원 밖 건강관리’ 서비스를 강조했다.",
    "news_url": "https://kormedi.com/2758726/",
    "demand": ["소비자(환자)", "의료기관"],
    "supply": ["플랫폼/서비스", "AI/데이터기업"],
    "type": "디지털 헬스 루프",
    "domain": "만성질환·예방의료",
    "entity": ["카카오헬스케어"],
    "region": "국내",
    "category": "제품/서비스 출시",
    "service_form": "모바일 앱+AI 예측",
    "summary": "카카오헬스케어가 병원 밖에서도 데이터를 기반으로 질병 예방과 조기 개입을 지원하는 헬스 루프 서비스를 추진한다."
  },
  {
    "post_id": "443146571",
    "post_title": "25.10.23 목 업계 동향입니다.",
    "post_date": "2025-10-23",
    "source_url": "https://kakaohealthcare.agit.in/g/300070906/wall/443146571",
    "news_title": "4. 카카오벤처스 인사이트 데이",
    "news_content": "의료 AI 상용화와 병원 내 신뢰 확보 방안을 주제로 카카오벤처스가 인사이트 데이를 개최했다.",
    "news_url": "https://v.daum.net/v/20251022164802156",
    "demand": ["의료기관", "연구기관/공공"],
    "supply": ["AI/데이터기업"],
    "type": "AI 의료 컨퍼런스",
    "domain": "의료AI·병원IT",
    "entity": ["카카오벤처스", "삼성서울병원"],
    "region": "국내",
    "category": "연구/임상/성과",
    "service_form": "컨퍼런스",
    "summary": "의료기관과 기업이 참여해 AI 의료기술의 병원 내 적용 전략과 신뢰성 확보를 논의했다."
  },
  {
    "post_id": "443409835",
    "post_title": "25.10.27 월 업계 동향입니다.",
    "post_date": "2025-10-27",
    "source_url": "https://kakaohealthcare.agit.in/g/300070906/wall/443409835",
    "news_title": "6. 걷기 공공 민간 앱 경쟁",
    "news_content": "공공기관과 민간기업이 각각 걷기 앱을 출시하며 국민 건강 증진을 위한 경쟁이 본격화됐다.",
    "news_url": "https://v.daum.net/v/20251026120001236",
    "demand": ["소비자(일반)", "연구기관/공공"],
    "supply": ["플랫폼/서비스"],
    "type": "건강 리워드 앱",
    "domain": "건강습관·운동",
    "entity": ["캐시워크", "서울시"],
    "region": "국내",
    "category": "보험/금융/건강관리",
    "service_form": "모바일 앱",
    "summary": "공공과 민간이 협력 혹은 경쟁하며 건강 리워드 기반의 걷기 앱 시장이 확장되고 있다."
  }
]
